import { devTool } from './dev-tools.mjs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { CHAPTERS, DURATION, sampleState } from './simulation.mjs';
const root=dirname(fileURLToPath(import.meta.url));
const {chromium}=devTool('playwright');
const out=resolve(root,'exports');await mkdir(out,{recursive:true});
assert.equal(CHAPTERS.length*DURATION,70);
assert.equal(sampleState(1,10).moisture,24);
assert.equal(sampleState(3,0).pump,true);
assert.equal(sampleState(3,10).pump,false);
assert.equal(sampleState(5,5).internet,false);
assert.equal(sampleState(5,10).buffered,0);
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4175');
await page.waitForFunction(()=>!!window.farmDemo,{timeout:30000});
await page.screenshot({path:resolve(out,'overview.png')});
for(let i=0;i<7;i++){
  await page.locator('#chapters button').nth(i).click();
  await page.waitForTimeout(2400);
  assert.equal(await page.locator('#chapter-no').innerText(),`${String(i+1).padStart(2,'0')} / 07`);
  if([3,4,5].includes(i))await page.screenshot({path:resolve(out,`chapter-${i+1}.png`)});
}
await page.locator('#restart').click();await page.waitForTimeout(2300);
const visible=page.locator('.equipment-label:visible');assert.ok(await visible.count()>0);
await visible.first().click();assert.equal(await page.locator('#inspector').isVisible(),true);await page.locator('#close-inspector').click();
await page.locator('#label-toggle').click();await page.waitForTimeout(200);assert.equal(await visible.count(),0);await page.locator('#label-toggle').click();
await page.locator('#play').click();await page.waitForTimeout(1000);await page.locator('#play').click();const paused=await page.evaluate(()=>window.farmDemo.getState());await page.waitForTimeout(300);assert.equal((await page.evaluate(()=>window.farmDemo.getState())).elapsed,paused.elapsed);
await page.locator('#restart').click();await page.waitForTimeout(2300);await page.locator('#clean').click();assert.equal(await page.locator('.director').isVisible(),false);await page.screenshot({path:resolve(out,'presentation-view.png')});await page.keyboard.press('h');assert.equal(await page.locator('.director').isVisible(),true);
const downloadPromise=page.waitForEvent('download');await page.locator('#export-model').click();const download=await downloadPromise;await download.saveAs(resolve(out,'okradesu-connected-field.glb'));
await page.setViewportSize({width:390,height:900});await page.waitForTimeout(1000);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:resolve(out,'mobile.png')});
assert.deepEqual(errors,[]);
const diagnostics=await page.evaluate(()=>window.farmDemo.getState());
await page.context().setOffline(true);
await page.goto(pathToFileURL(resolve(root,'index.html')).href);
await page.waitForFunction(()=>!!window.farmDemo);
assert.equal(await page.locator('#error').isVisible(),false);
await page.setViewportSize({width:1920,height:1080});
await page.locator('#clean').click();
await page.screenshot({path:resolve(out,'presentation-view.png')});
await page.keyboard.press('h');
await page.locator('#chapters button').nth(3).click();
await page.waitForTimeout(2500);
await page.locator('#clean').click();
await page.screenshot({path:resolve(out,'irrigation-presentation.png')});
assert.deepEqual(errors,[]);
await writeFile(resolve(out,'verification.json'),JSON.stringify({passed:true,browser:'Chrome',checked:['7 chapters','scenario rules','equipment inspector','labels','play/pause','recording view','GLB export','390px layout','file:// offline launch','1920x1080 recording view'],errors,diagnostics},null,2));
await browser.close();console.log('PASS: scenarios, controls, export, responsive layout. Screenshots in exports/.');
